/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BooksRouteImport } from './routes/books'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicReturnsRouteImport } from './routes/api/public/returns'
import { Route as ApiPublicBookingsRouteImport } from './routes/api/public/bookings'
import { Route as ApiPublicBooksAvailableRouteImport } from './routes/api/public/books/available'

const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReturnsRoute = ApiPublicReturnsRouteImport.update({
  id: '/api/public/returns',
  path: '/api/public/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingsRoute = ApiPublicBookingsRouteImport.update({
  id: '/api/public/bookings',
  path: '/api/public/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBooksAvailableRoute = ApiPublicBooksAvailableRouteImport.update({
  id: '/api/public/books/available',
  path: '/api/public/books/available',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/books': typeof BooksRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/api/public/returns': typeof ApiPublicReturnsRoute
  '/api/public/books/available': typeof ApiPublicBooksAvailableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/books': typeof BooksRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/api/public/returns': typeof ApiPublicReturnsRoute
  '/api/public/books/available': typeof ApiPublicBooksAvailableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/books': typeof BooksRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/api/public/returns': typeof ApiPublicReturnsRoute
  '/api/public/books/available': typeof ApiPublicBooksAvailableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/books'
    | '/api/public/bookings'
    | '/api/public/returns'
    | '/api/public/books/available'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/books'
    | '/api/public/bookings'
    | '/api/public/returns'
    | '/api/public/books/available'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/books'
    | '/api/public/bookings'
    | '/api/public/returns'
    | '/api/public/books/available'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  BooksRoute: typeof BooksRoute
  ApiPublicBookingsRoute: typeof ApiPublicBookingsRoute
  ApiPublicReturnsRoute: typeof ApiPublicReturnsRoute
  ApiPublicBooksAvailableRoute: typeof ApiPublicBooksAvailableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/returns': {
      id: '/api/public/returns'
      path: '/api/public/returns'
      fullPath: '/api/public/returns'
      preLoaderRoute: typeof ApiPublicReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookings': {
      id: '/api/public/bookings'
      path: '/api/public/bookings'
      fullPath: '/api/public/bookings'
      preLoaderRoute: typeof ApiPublicBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/books/available': {
      id: '/api/public/books/available'
      path: '/api/public/books/available'
      fullPath: '/api/public/books/available'
      preLoaderRoute: typeof ApiPublicBooksAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  BooksRoute: BooksRoute,
  ApiPublicBookingsRoute: ApiPublicBookingsRoute,
  ApiPublicReturnsRoute: ApiPublicReturnsRoute,
  ApiPublicBooksAvailableRoute: ApiPublicBooksAvailableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
